name: crud_flutter
description: CRUD Flutter Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter  
  path: ^1.8.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  mysql1: ^0.20.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true